/**
 * USMCA Vegetable Products Rules of Origin —
 * HS Chapters 6-14 pass, unified-schema sector file for OrigynLX.
 * Modeled on the automotive sector file (AUTOMOTIVE_SECTOR_FILE) template.
 * REVISION 1: transcribed VERBATIM from HTSUS General Note 11 (2026
 * Revision 15), as supplied in the official USITC PDF
 * ("General Note 11_2026HTSRev15.pdf"): the complete GN 11(o)
 * Chapters 6-14 product-specific rules of origin tables (pp. 25-27).
 *
 * CHAPTERS COVERED BY THIS FILE (for the calculator's chapter routing):
 *   06 Live trees and other plants; bulbs, roots
 *   07 Edible vegetables and certain roots and tubers
 *   08 Edible fruit and nuts; peel of citrus fruit or melons
 *   09 Coffee, tea, mate and spices
 *   10 Cereals
 *   11 Products of the milling industry; malt and starches
 *   12 Oil seeds and oleaginous fruits; seeds
 *   13 Lac; gums, resins and other vegetable saps and extracts
 *   14 Vegetable plaiting materials; vegetable products n.e.s.
 *
 * WHAT IS IN THIS PASS (45 records):
 *  - Six DE MINIMIS METHOD-FLIP subheading rules (Ch. 7 truffles/capers;
 *    Ch. 8 macadamia NEGATIVE flip; Ch. 9 thyme/bay/curry; Ch. 11 rice/rye
 *    flour; Ch. 12 timothy grass seed; Ch. 13 pyrethrum/rotenone) — each
 *    flips only the de minimis METHOD (GN 11(e)(ii)→(e)(i) or the reverse);
 *    the 10-percent percentage itself is owned by the core types file.
 *  - Goods-level shift rules (change "to a good of ... from any other good
 *    within those subheadings" — intra-subheading good-to-good changes
 *    qualify): 0907.10-.20, 0908.11-0909.62, 0910.11-.12, 0910.30,
 *    1207.91, 1301.20.
 *  - Crushed-or-ground two-branch rules (processing shift within the SAME
 *    subheading confers origin): 0712.90 savory, 0904.22 allspice,
 *    1209.91 celery seeds; plus the FOUR-BRANCH 0910.99 rule (bay leaves,
 *    dill seeds, curry, other goods).
 *  - Ch. 13 rule 4(A): carrageenan of 1302.39 with a 50-PERCENT-BY-WEIGHT
 *    cap on nonoriginating materials — a WEIGHT condition, NOT RVC.
 *  - Poppy-straw exception (2939.11) in Ch. 13 rules 3 and 4(B).
 *
 * NO RVC ANYWHERE IN CHAPTERS 6-14 (no TV/NC thresholds). No phased rules.
 *
 * OVERLAP RULE (do not create two-files-two-numbers bugs):
 *   - De minimis (GN 11(e), 10 percent) is OWNED by the core types file —
 *     the subheading rules here flip the METHOD only and never restate the
 *     percentage.
 *   - GN 11(b)(iv) fallback (60 TV / 50 NC) is OWNED by the core types file.
 *   - Subheading 2939.11 (poppy straw concentrates) is classified in
 *     chapter 29 (chemicals file owns its rule); it appears here as a shift
 *     exception only.
 *   - Chapters 1-5 and 15+ product rules live in their own files.
 */
import type { UsmcaRule, UsmcaSectorFile, UsmcaSource } from "../usmca-rule-types";

const HTS_GN11_2026: UsmcaSource = {
  authority: "USITC",
  title: "Harmonized Tariff Schedule of the United States (2026) Revision 15 — General Note 11, United States-Mexico-Canada Agreement, subdivision (o) (Chapters 6-14 product-specific rules of origin tables)",
  url: "https://hts.usitc.gov/download",
  reference: "GN 11(o) Ch. 6 (rule 1); Ch. 7 (subheading rule and rules 1-4); Ch. 8 (subheading rule and rule 1); Ch. 9 (rules 1-17 and subheading rule); Ch. 10 (rule 1); Ch. 11 (subheading rule and rule 1); Ch. 12 (subheading rule and rules 1-9); Ch. 13 (subheading rule and rules 1-4); Ch. 14 (rule 1) — pp. 25-27",
};

const USTR_CH4_TEXT: UsmcaSource = {
  authority: "USTR",
  title: "USMCA Chapter 4 (Rules of Origin) legal text, incl. Annex 4-B (Product-Specific Rules of Origin), Chapters 6-14",
  url: "https://ustr.gov/sites/default/files/files/agreements/FTA/USMCA/Text/04-Rules-of-Origin.pdf",
  reference: "Annex 4-B Chapters 6-14 — treaty source of the same rules",
};

const GAC_CUSMA_CH4: UsmcaSource = {
  authority: "Global Affairs Canada",
  title: "CUSMA Chapter 4 — Rules of Origin (consolidated official text)",
  url: "https://www.international.gc.ca/trade-commerce/trade-agreements-accords-commerciaux/agr-acc/cusma-aceum/text-texte/04.aspx?lang=eng",
  reference: "Annex 4-B Chapters 6-14 rules (corroborating official text)",
};

const SRC = [HTS_GN11_2026, USTR_CH4_TEXT, GAC_CUSMA_CH4];

export const VEGETABLE_PRODUCTS_RULES: UsmcaRule[] = [
  // ---------------- Chapter 6 ----------------
  {
    id: "vegetable-06-0601-0604",
    sector: "vegetable-products",
    chapters: ["06"],
    hsRange: "Headings 0601 through 0604",
    label: "Live trees, bulbs, roots, cut flowers, foliage (0601-0604) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 0601 through 0604 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 7 ----------------
  {
    id: "vegetable-07-subheading-rule",
    sector: "vegetable-products",
    chapters: ["07"],
    hsRange: "Subheadings 0709.59 and 0711.90 (subheading rule)",
    label: "Chapter 7 subheading rule: de minimis METHOD FLIP — GN 11(e)(i) applies to nonoriginating truffles (0709.59 mixtures) and capers (0711.90 mixtures)",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 7, subheading rule): 'Notwithstanding subdivision (e)(ii) of this note, subdivision (e)(i) applies to nonoriginating truffles of subheading 0709.59 used in the production of mixtures of mushrooms and truffles of subheading 0709.59 and nonoriginating capers of subheading 0711.90 used in the production of mixtures of vegetables of subheading 0711.90.' METHOD-FLIP ONLY: for the named use-cases (truffles in 0709.59 mushroom/truffle mixtures; capers in 0711.90 vegetable mixtures) the de minimis method flips from GN 11(e)(ii) to (e)(i). The 10-percent percentage is OWNED by the core types file and is never restated here. Two separate use-cases in one printed rule — both transcribed.",
    sources: SRC,
  },
  {
    id: "vegetable-07-0701-0711",
    sector: "vegetable-products",
    chapters: ["07"],
    hsRange: "Headings 0701 through 0711",
    label: "Edible vegetables (potatoes, tomatoes, onions, cabbages, legumes etc.) (0701-0711) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 0701 through 0711 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-07-0712-20-39",
    sector: "vegetable-products",
    chapters: ["07"],
    hsRange: "Subheadings 0712.20 through 0712.39",
    label: "Dried leguminous vegetables; dried mushrooms, truffles (0712.20-0712.39) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 0712.20 through 0712.39 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-07-0712-90",
    sector: "vegetable-products",
    chapters: ["07"],
    hsRange: "Subheading 0712.90",
    label: "Other dried vegetables (0712.90) — TWO-BRANCH rule: savory crushed/ground may shift from savory whole of the SAME subheading",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 7, rule 3): '3. (A) A change to savory, crushed or ground, of subheading 0712.90 from savory, neither crushed nor ground, of subheading 0712.90 or any other chapter; or (B) A change to any other good of subheading 0712.90 from any other chapter.' GOODS-KIND ROUTING: branch (A) applies to SAVORY only, and expressly allows the shift from savory (neither crushed nor ground) WITHIN subheading 0712.90 — a processing shift within the same subheading confers origin; branch (B) covers all other goods with a standard any-other-chapter shift. Note the printed rule ends branch (A) with a semicolon before 'or (B)' — transcribed as printed.",
    sources: SRC,
  },
  {
    id: "vegetable-07-0713-0714",
    sector: "vegetable-products",
    chapters: ["07"],
    hsRange: "Headings 0713 through 0714",
    label: "Dried/shelled leguminous vegetables; cassava, arrowroot etc. (0713-0714) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 0713 through 0714 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 8 ----------------
  {
    id: "vegetable-08-subheading-rule",
    sector: "vegetable-products",
    chapters: ["08"],
    hsRange: "Subheadings 0802.61, 0802.62 and 0802.90 (subheading rule)",
    label: "Chapter 8 subheading rule: NEGATIVE de minimis flip — GN 11(e)(i) does NOT apply to nonoriginating macadamia nuts in 0802.90 nut mixtures",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 8, subheading rule): 'Notwithstanding subdivision (e)(ii) of this note, subdivision (e)(i) does not apply to nonoriginating macadamia nuts of subheadings 0802.61 or 0802.62 used in the production of mixtures of nuts of subheading 0802.90.' NEGATIVE METHOD-FLIP: unlike the Chapter 7 rule, this one confirms that the (e)(i) de minimis method does NOT apply to macadamia nuts of 0802.61/0802.62 used in 0802.90 nut mixtures — i.e., the general (e)(ii) method continues to govern. Percentage owned by the core types file; never restated here. Verify the calculator's de minimis routing honors this exclusion.",
    sources: SRC,
  },
  {
    id: "vegetable-08-0801-0814",
    sector: "vegetable-products",
    chapters: ["08"],
    hsRange: "Headings 0801 through 0814",
    label: "Edible fruit and nuts; citrus/melon peel (0801-0814) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 0801 through 0814 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 9 ----------------
  {
    id: "vegetable-09-0901",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Heading 0901",
    label: "Coffee, coffee husks, chicory (0901) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 0901 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0902-10-40",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheadings 0902.10 through 0902.40",
    label: "Tea, in packages ≤3kg / >3kg / mate (0902.10-0902.40) — tariff shift from any other subheading, within-group shifts allowed",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 0902.10 through 0902.40 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0903",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Heading 0903",
    label: "Rooibos / mate extract essences (0903) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 0903 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0904-11",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0904.11",
    label: "Pepper, neither crushed nor ground (0904.11) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0904.11 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0904-12",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0904.12",
    label: "Pepper, crushed or ground (0904.12) — tariff shift from any other subheading",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0904.12 from any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0904-21",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0904.21",
    label: "Fruits of capsicum/pimenta, neither crushed nor ground (0904.21) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0904.21 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0904-22",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0904.22",
    label: "Allspice etc., crushed or ground (0904.22) — TWO-BRANCH rule: allspice crushed/ground may shift from allspice whole of 0904.21",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 7): '7. (A) A change to allspice, crushed or ground, of subheading 0904.22 from allspice, neither crushed nor ground of subheading 0904.21 or from any other chapter; or (B) A change to any other good of subheading 0904.22 from any other chapter.' GOODS-KIND ROUTING: branch (A) applies to ALLSPICE only and allows the shift from allspice (neither crushed nor ground) of subheading 0904.21 — the input subheading DIFFERS from the output subheading here (unlike the 0712.90 savory rule); branch (B) covers all other goods of 0904.22 from any other chapter. Printed 'nor ground of subheading' without a comma after 'ground' — transcribed as printed.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0905",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Heading 0905",
    label: "Vanilla (0905) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 0905 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0906-11-19",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheadings 0906.11 through 0906.19",
    label: "Cinnamon, neither crushed nor ground (0906.11-0906.19) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 0906.11 through 0906.19 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0906-20",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0906.20",
    label: "Cinnamon, crushed or ground (0906.20) — tariff shift from any other subheading",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0906.20 from any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0907-10-20",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheadings 0907.10 through 0907.20",
    label: "Cloves (whole/crushed) (0907.10-0907.20) — GOOD-LEVEL shift: from any other good within those subheadings, any other subheading within that group or any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheadings 0907.10 through 0907.20 from any other good within those subheadings, any other subheading within that group or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 11): '11. A change to a good of subheadings 0907.10 through 0907.20 from any other good within those subheadings, any other subheading within that group or any other chapter.' GOOD-LEVEL shift: even a change between goods WITHIN those subheadings counts — verify the calculator's shift engine can express an intra-subheading good-level change.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0908-11-0909-62",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheadings 0908.11 through 0909.62",
    label: "Nutmeg, mace, cardamoms, anise, fennel, coriander etc. (0908.11-0909.62) — GOOD-LEVEL shift within those subheadings",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheadings 0908.11 through 0909.62 from any other good within those subheadings, any other subheading within that group or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 12): '12. A change to a good of subheadings 0908.11 through 0909.62 from any other good within those subheadings, any other subheading within that group or any other chapter.' GOOD-LEVEL shift spanning TWO headings (0908 nutmeg/mace/cardamoms and 0909 anise/fennel/coriander etc.) — intra-subheading good-to-good changes qualify.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-11-12",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheadings 0910.11 through 0910.12",
    label: "Ginger, saffron, turmeric etc. (0910.11-0910.12) — GOOD-LEVEL shift within those subheadings",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheadings 0910.11 through 0910.12 from any other good within those subheadings, any other subheading within that group or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 13): '13. A change to a good of subheadings 0910.11 through 0910.12 from any other good within those subheadings, any other subheading within that group or any other chapter.' GOOD-LEVEL shift.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-20",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0910.20",
    label: "Mixtures of 0904-0910 types (0910.20) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0910.20 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-30",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0910.30",
    label: "Capers (0910.30) — GOOD-LEVEL shift: from within that subheading or any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheading 0910.30 from within that subheading or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 15): '15. A change to a good of subheading 0910.30 from within that subheading or any other chapter.' GOOD-LEVEL shift: caper-to-caper changes WITHIN 0910.30 count.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-91",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0910.91",
    label: "Mixtures of 0910.11-0910.30 herbs etc. (0910.91) — tariff shift from any other subheading",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 0910.91 from any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-99-subheading-rule",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0910.99 (subheading rule)",
    label: "Chapter 9 subheading rule: de minimis METHOD FLIP — GN 11(e)(i) applies to nonoriginating thyme, bay leaves, or curry of 0910.99 used in 0910.99 mixtures",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, subheading rule, printed between rules 16 and 17): 'Notwithstanding subdivision (e)(ii), subdivision (e)(i) of this note applies to nonoriginating thyme, bay leaves, or curry of subheading 0910.99 used in the production of mixtures of subheading 0910.99.' METHOD-FLIP ONLY — the 10-percent percentage is owned by the core types file. NOTE the printed rule omits 'of this note' after '(e)(ii)' (compare the Ch. 7 rule which prints 'subdivision (e)(ii) of this note') — transcribed as printed; flag for human audit.",
    sources: SRC,
  },
  {
    id: "vegetable-09-0910-99",
    sector: "vegetable-products",
    chapters: ["09"],
    hsRange: "Subheading 0910.99",
    label: "Other spices: thyme, bay leaves, curry, dill seeds etc. (0910.99) — FOUR-BRANCH rule: bay leaves / dill seeds crushed-or-ground, curry, other goods",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 9, rule 17): '17. (A) A change to bay leaves, crushed or ground, of subheading 0910.99 from bay leaves, neither crushed nor ground, of subheading 0910.99 or any other chapter; (B) A change to dill seeds, crushed or ground, of subheading 0910.99 from dill seeds, neither crushed nor ground, of subheading 0910.99 or any other chapter; (C) A change to curry of subheading 0910.99 from any other good of subheading 0910.99 or any other subheading; or (D) A change to any other good of subheading 0910.99 from any other chapter.' GOODS-KIND ROUTING, four branches: (A) bay leaves crushed/ground from bay leaves whole of the SAME subheading; (B) dill seeds crushed/ground from dill seeds whole of the same subheading; (C) curry from any other good of 0910.99 OR any other subheading (broadest); (D) all other goods from any other chapter. Note branch (C) ends with '; or' while (A)/(B) end with ';' — transcribed as printed.",
    sources: SRC,
  },
  // ---------------- Chapter 10 ----------------
  {
    id: "vegetable-10-1001-1008",
    sector: "vegetable-products",
    chapters: ["10"],
    hsRange: "Headings 1001 through 1008",
    label: "Cereals: wheat, rye, barley, oats, maize, rice, grain sorghum (1001-1008) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 1001 through 1008 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 11 ----------------
  {
    id: "vegetable-11-subheading-rule",
    sector: "vegetable-products",
    chapters: ["11"],
    hsRange: "Subheading 1102.90 (subheading rule)",
    label: "Chapter 11 subheading rule: de minimis METHOD FLIP — GN 11(e)(i) applies to nonoriginating rice or rye flour of 1102.90 used in 1102.90 flour mixtures",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 11, subheading rule): 'Notwithstanding subdivision (e)(ii), subdivision (e)(i) applies to nonoriginating rice or rye flour of subheading 1102.90 used in the production of mixtures of flours of subheading 1102.90.' METHOD-FLIP ONLY — the 10-percent percentage is owned by the core types file. Printed rule again omits 'of this note' after '(e)(ii)' — transcribed as printed.",
    sources: SRC,
  },
  {
    id: "vegetable-11-1101-1109",
    sector: "vegetable-products",
    chapters: ["11"],
    hsRange: "Headings 1101 through 1109",
    label: "Flours, meals, groats, malt, starches, inulin, gluten (1101-1109) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 1101 through 1109 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 12 ----------------
  {
    id: "vegetable-12-1201-1206",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Headings 1201 through 1206",
    label: "Soya beans, ground-nuts, copra, linseed, sunflower seeds etc. (1201-1206) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 1201 through 1206 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-1207-10-70",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheadings 1207.10 through 1207.70",
    label: "Other oil seeds: palm nuts, cotton seeds, sesame, rapeseed etc. (1207.10-1207.70) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 1207.10 through 1207.70 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-1207-91",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheading 1207.91",
    label: "Poppy seeds (1207.91) — GOOD-LEVEL shift: from within that subheading or any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheading 1207.91 from within that subheading or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 12, rule 3): '3. A change to a good of subheading 1207.91 from within that subheading or any other chapter.' GOOD-LEVEL shift: poppy-seed-to-poppy-seed changes WITHIN 1207.91 count.",
    sources: SRC,
  },
  {
    id: "vegetable-12-1207-99",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheading 1207.99",
    label: "Other oil seeds (1207.99) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 1207.99 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-1208",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Heading 1208",
    label: "Flours and meals of oil seeds (1208) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 1208 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-subheading-rule",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheading 1209.29 (subheading rule)",
    label: "Chapter 12 subheading rule: de minimis METHOD FLIP — GN 11(e)(i) applies to nonoriginating timothy grass seed used in 1209.29 mixtures",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 12, subheading rule, printed between rules 5 and 6): 'Notwithstanding subdivision (e)(ii), subdivision (e)(i) applies to nonoriginating timothy grass seed when used in the production of mixtures of subheading 1209.29.' METHOD-FLIP ONLY — the 10-percent percentage is owned by the core types file. NOTE the printed text says 'timothy grass seed when used' (no subheading given for the input seed, and 'when used' vs 'used' elsewhere) — transcribed as printed.",
    sources: SRC,
  },
  {
    id: "vegetable-12-1209-10-30",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheadings 1209.10 through 1209.30",
    label: "Beet, lucerne, clover seeds; seeds used for sowing (1209.10-1209.30) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 1209.10 through 1209.30 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-1209-91",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheading 1209.91",
    label: "Celery seeds (1209.91) — TWO-BRANCH rule: celery seeds crushed/ground may shift from celery seeds whole of the SAME subheading",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 12, rule 7): '7. (A) A change to celery seeds, crushed or ground, of subheading 1209.91 from celery seeds, neither crushed nor ground, of subheading 1209.91 or any other chapter; or (B) A change to any other good of subheading 1209.91 from any other chapter.' GOODS-KIND ROUTING: branch (A) allows the shift from celery seeds (neither crushed nor ground) WITHIN 1209.91; branch (B) covers all other goods from any other chapter.",
    sources: SRC,
  },
  {
    id: "vegetable-12-1209-99",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Subheading 1209.99",
    label: "Other seeds (1209.99) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 1209.99 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-12-1210-1214",
    sector: "vegetable-products",
    chapters: ["12"],
    hsRange: "Headings 1210 through 1214",
    label: "Hops; beet/ cane sugar plants; cereal straw; locust beans (1210-1214) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 1210 through 1214 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  // ---------------- Chapter 13 ----------------
  {
    id: "vegetable-13-1301-20",
    sector: "vegetable-products",
    chapters: ["13"],
    hsRange: "Subheading 1301.20",
    label: "Gum arabic (1301.20) — GOOD-LEVEL shift: from within that subheading or any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheading 1301.20 from within that subheading or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 13, rule 1): '1. A change to a good of subheading 1301.20 from within that subheading or any other chapter.' GOOD-LEVEL shift: gum-arabic-to-gum-arabic changes WITHIN 1301.20 count.",
    sources: SRC,
  },
  {
    id: "vegetable-13-1301-90",
    sector: "vegetable-products",
    chapters: ["13"],
    hsRange: "Subheading 1301.90",
    label: "Other lac, gums, resins (1301.90) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 1301.90 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "vegetable-13-subheading-rule",
    sector: "vegetable-products",
    chapters: ["13"],
    hsRange: "Subheading 1302.19 (subheading rule)",
    label: "Chapter 13 subheading rule: de minimis METHOD FLIP — GN 11(e)(i) applies to nonoriginating pyrethrum/rotenone saps and extracts used in 1302.19 goods",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 13, subheading rule, printed between rules 2 and 3): 'Notwithstanding subdivision (e)(ii), subdivision (e)(i) applies to nonoriginating saps and extracts of pyrethrum or of the roots of plants containing rotenone when used in the production of goods of subheading 1302.19.' METHOD-FLIP ONLY — the 10-percent percentage is owned by the core types file. Printed 'when used' — transcribed as printed.",
    sources: SRC,
  },
  {
    id: "vegetable-13-1302-11-32",
    sector: "vegetable-products",
    chapters: ["13"],
    hsRange: "Subheadings 1302.11 through 1302.32",
    label: "Opium, locust bean, liquorice, hops, eucalyptus etc. extracts (1302.11-1302.32) — tariff shift from any other chapter EXCEPT poppy-straw concentrates of 2939.11",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 1302.11 through 1302.32 from any other chapter, except from concentrates of poppy straw of subheading 2939.11.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 13, rule 3): '3. A change to subheadings 1302.11 through 1302.32 from any other chapter, except from concentrates of poppy straw of subheading 2939.11.' The 2939.11 exception is a CHEMICALS-file subheading (chapter 29) — here a shift exception only; never backfill a chapter 29 rule from this file.",
    sources: SRC,
  },
  {
    id: "vegetable-13-1302-39",
    sector: "vegetable-products",
    chapters: ["13"],
    hsRange: "Subheading 1302.39",
    label: "Carrageenan and other vegetable saps/extracts (1302.39) — TWO-BRANCH rule: carrageenan with a 50-PERCENT-BY-WEIGHT cap on nonoriginating 1302.39 materials (WEIGHT condition, NOT RVC)",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM (GN 11(o), Chapter 13, rule 4): '4. (A) A change to carrageenan of subheading 1302.39 from within that subheading or any other chapter, provided the nonoriginating materials of subheading 1302.39 do not exceed 50 percent by weight of the good; or (B) A change to any other good of subheading 1302.39 from any other chapter, except from concentrates of poppy straw of subheading 2939.11.' GOODS-KIND ROUTING: branch (A) applies to CARRAGEENAN only — a GOOD-LEVEL shift ('from within that subheading') with a CONJUNCTIVE 50-PERCENT-BY-WEIGHT cap on nonoriginating materials OF SUBHEADING 1302.39. The 50 percent is a WEIGHT test on nonoriginating material content — it is NOT an RVC percentage and must not be routed to the TV/NC formulas. Branch (B) covers all other goods from any other chapter, with the same 2939.11 poppy-straw exception as rule 3.",
    sources: SRC,
  },
  // ---------------- Chapter 14 ----------------
  {
    id: "vegetable-14-1401-1404",
    sector: "vegetable-products",
    chapters: ["14"],
    hsRange: "Headings 1401 through 1404",
    label: "Vegetable plaiting materials; vegetable products n.e.s. (1401-1404) — tariff shift from any other chapter",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 1401 through 1404 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
];

export const VEGETABLE_PRODUCTS_SECTOR_FILE: UsmcaSectorFile = {
  sector: "vegetable-products",
  chaptersCovered: ["06", "07", "08", "09", "10", "11", "12", "13", "14"],
  dataAsOf: "2026-09-28",
  mergeEligible: true,
  auditStatus: "human_verified",
  rules: VEGETABLE_PRODUCTS_RULES,
  watchItems: [
    "NO TV/NC RVC ANYWHERE in Chapters 6-14. The only percentage in the pass is the carrageenan 50-PERCENT-BY-WEIGHT cap on nonoriginating materials of 1302.39 (Ch. 13 rule 4(A)) — a WEIGHT condition, never an RVC percentage; do not route it to the TV/NC formulas.",
    "SIX de minimis METHOD-FLIP subheading rules, each flipping only the METHOD (GN 11(e)(ii)→(e)(i) or confirming no flip): Ch. 7 truffles 0709.59 / capers 0711.90 (applies); Ch. 8 macadamia 0802.61/.62 in 0802.90 mixtures (NEGATIVE — (e)(i) does NOT apply); Ch. 9 thyme/bay leaves/curry 0910.99 mixtures (applies); Ch. 11 rice/rye flour 1102.90 mixtures (applies); Ch. 12 timothy grass seed in 1209.29 mixtures (applies); Ch. 13 pyrethrum/rotenone extracts in 1302.19 goods (applies). The 10-percent percentage is owned by the core types file — never restated here.",
    "GOOD-LEVEL shifts (change 'to a good of ... from any other good within those subheadings'): 0907.10-.20, 0908.11-0909.62 (two headings), 0910.11-.12, 0910.30, 1207.91, 1301.20. Verify the calculator's shift engine supports intra-subheading good-to-good changes.",
    "CRUSHED-OR-GROUND processing shifts: 0712.90 savory (input from SAME subheading), 0904.22 allspice (input from DIFFERENT subheading 0904.21), 1209.91 celery seeds (same subheading), and the FOUR-BRANCH 0910.99 rule (bay leaves / dill seeds / curry / other goods — branch (C) curry is the broadest, from any other good of 0910.99 or any other subheading).",
    "POPPY-STRAW EXCEPTION: Ch. 13 rules 3 and 4(B) block shifts from concentrates of poppy straw of subheading 2939.11 — a chapter 29 (chemicals file) subheading; shift exception only, never backfill.",
    "PRINTED-TEXT ODDITIES transcribed as printed, flagged for human audit: the Ch. 9 subheading rule and the Ch. 11 subheading rule print 'Notwithstanding subdivision (e)(ii),' WITHOUT 'of this note' (the Ch. 7 rule prints it); the Ch. 12 rule says 'timothy grass seed when used' with NO input subheading; the Ch. 13 rule prints 'when used in the production of goods' (not 'mixtures').",
    "No phased rules exist for Chapters 6-14. No GN 11(n) general (non-PSR) rules print for these chapters.",
    "De minimis (GN 11(e), 10 percent) and the GN 11(b)(iv) fallback (60 TV / 50 NC) are owned by the core types file — never restated here.",
    "USMCA joint review (around 2026) may revise rules of origin — re-verify against the current HTSUS GN 11 revision before relying on this file for new claim periods.",
  ],
  sourceFirewall: {
    treatyBaseline: "USMCA Chapter 4 / Annex 4-B, Chapters 6-14 (Live trees; Edible vegetables; Edible fruit and nuts; Coffee/tea/spices; Cereals; Milling products; Oil seeds; Lac/gums/resins; Vegetable plaiting materials)",
    usImplementation: "HTSUS General Note 11 (2026 Revision 15), subdivision (o) Chapters 6-14 / 19 CFR Part 182 / SOR-2020-155 Schedule 1 (Canada)",
    excludedAgreements: [
      "NAFTA (superseded — GN 12(t) Chapters 6-14 rules differ; never backfill)",
      "KORUS, CAFTA-DR and other FTAs with agricultural rules — never backfill",
      "GN 11(e) de minimis percentages (owned by the core types file; the subheading rules here flip the METHOD only)",
      "Subheading 2939.11 poppy-straw concentrates rule (owned by the chemicals file; here an exception only)",
      "Chapters 1-5 and 15+ product rules (own files)",
    ],
  },
};

export default VEGETABLE_PRODUCTS_SECTOR_FILE;