/**
 * USMCA Base Metals & Articles of Base Metal Rules of Origin —
 * HS Section XV pass (Chapters 72-83), unified-schema sector file for OrigynLX.
 * Modeled on the automotive sector file (AUTOMOTIVE_SECTOR_FILE) template.
 *
 * SOURCE OF RECORD FOR THIS PASS: HTSUS General Note 11 (USMCA), Revision 15
 * (2026), subdivision (o) product-specific rules of origin, Chapters 72-83
 * (user-supplied official USITC PDF, "General Note 11_2026HTSRev15.pdf").
 * ALL rule text below is VERBATIM from that document. RVC percentages are
 * computed per GN 11(c): TV method RVC = ((TV-VNM)/TV) x 100; NC method
 * RVC = ((NC-VNM)/NC) x 100.
 *
 * CHAPTERS COVERED BY THIS FILE (for the calculator's chapter routing):
 *   72 Iron and steel
 *   73 Articles of iron or steel
 *   74 Copper and articles of copper
 *   75 Nickel and articles of nickel
 *   76 Aluminum and articles of aluminum
 *   78 Lead and articles of lead
 *   79 Zinc and articles of zinc
 *   80 Tin and articles of tin
 *   81 Other base metals; cermets; articles thereof
 *   82 Tools, implements, cutlery, spoons and forks, of base metal
 *   83 Miscellaneous articles of base metal
 *   (HS Chapter 77 is reserved and does not exist — deliberately absent.)
 *
 * DATE-SENSITIVE PHASED RULES (the calculator MUST select by entry date):
 *   - Headings 7305-7307 and several 73.08-73.17 subheading/heading rules are
 *     TWO-PHASE: a liberal early rule (2020-07-01 through 2022-06-30 or
 *     2023-06-30, per rule) and a stricter later rule with three alternative
 *     routes: (a) tariff shift excluding headings 7208-7229 / 7301-7326,
 *     (b) change from those headings provided at least 70 percent BY WEIGHT of
 *     the materials of those headings is originating, or (c) no change in
 *     tariff classification provided RVC thresholds are met. As of this file's
 *     dataAsOf date (2026-09-28) ONLY the later rules are in force; the early
 *     phases are retained for historical/audit entries.
 *   - The GN 11(b)(iv) fallback (goods produced entirely in USMCA territory
 *     whose parts fail the PSRO only because of same-subheading classification
 *     or GRI 2(a) unassembled import: RVC >= 60 percent TV / 50 percent NC) is
 *     OWNED by the core rules-of-origin types file and is NOT restated here.
 *
 * OVERLAP WARNING (two-files-two-numbers prevention):
 *   - Chapter 83 Chapter rule 1 (verbatim below) routes underscored
 *     designations (subheading 8301.10-8301.50) used in a motor vehicle of
 *     chapter 87 to subdivision (k) of GN 11 — the automotive parts regime
 *     owned by the AUTOMOTIVE_SECTOR_FILE. No automotive thresholds are
 *     restated here.
 *   - Section 232 steel/aluminum actions are a separate national-security
 *     tariff regime; a Chapter 72/73/76 good can be fully USMCA-originating
 *     and still owe Section 232 duties. See watchItems.
 */
import type { UsmcaRule, UsmcaSectorFile, UsmcaSource } from "../usmca-rule-types";

const HTS_GN11_2026: UsmcaSource = {
  authority: "USITC",
  title: "Harmonized Tariff Schedule of the United States (2026) Revision 15 — General Note 11, United States-Mexico-Canada Agreement, subdivision (o) (Chapters 72-83)",
  url: "https://hts.usitc.gov/download",
  reference: "GN 11(o) product-specific rules of origin for Chapters 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, incl. heading/subheading rules with effective-date phases; GN 11(c) RVC formulas; GN 11(b)(iv) fallback (owned by core file); GN 11(k) automotive-parts carryover (owned by automotive file)",
};

const ECFR_182: UsmcaSource = {
  authority: "eCFR (CBP regulations)",
  title: "19 CFR Part 182 — United States-Mexico-Canada Agreement",
  url: "https://www.ecfr.gov/current/title-19/chapter-I/part-182",
  reference: "U.S. implementing regulations for USMCA rules of origin (interpretive companion to GN 11; no thresholds restated here)",
};

const BASE_METALS_CHAPTERS: string[] = [
  "72", "73", "74", "75", "76", "78", "79", "80", "81", "82", "83",
];

const SRC = [HTS_GN11_2026];

export const BASE_METALS_RULES: UsmcaRule[] = [
  // ===================== CHAPTER 72 — IRON AND STEEL =====================
  {
    id: "metals-72-7201",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.01",
    label: "Pig iron and spiegeleisen",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7201 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7202-11-60",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "7202.11 through 7202.60",
    label: "Ferro-alloys (groups 7202.11-7202.60)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7202.11 through 7202.60 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7202-70",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "7202.70",
    label: "Ferro-silicon (7202.70) — except from molybdenum ores (2613.10)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7202.70 from any other chapter, except from subheading 2613.10.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7202-80-99",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "7202.80 through 7202.99",
    label: "Other ferro-alloys",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7202.80 through 7202.99 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7203-7205",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.03 through 72.05",
    label: "Ferrous waste and scrap; sponge iron; granules and powders",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7203 through 7205 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7206-7207",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.06 through 72.07",
    label: "Ingots and semi-finished iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7206 through 7207 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7208-7216",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.08 through 72.16",
    label: "Flat-rolled, bars and rods, angles and shapes of iron/steel (7208-7216 group)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7208 through 7216 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "This group (7208-7229, 7301-7326) is the 'steel inputs' family that the later phased Chapter 73 rules single out for the 70-percent-by-weight originating condition. Headings 7208-7229 are also referenced by the melted-and-poured automotive regime (owned by the automotive file).",
    sources: SRC,
  },
  {
    id: "metals-72-7217",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.17",
    label: "Wire of iron or steel — except from bars/rods 7213-7215",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7217 from any other heading, except from headings 7213 through 7215.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7218-7222",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.18 through 72.22",
    label: "Stainless steel and other alloy steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7218 through 7222 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7223",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.23",
    label: "Wire of stainless steel — except from 7221-7222",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7223 from any other heading, except from headings 7221 through 7222.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7224-7228",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.24 through 72.28",
    label: "Alloy steel flat-rolled, bars, hollow drill steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7224 through 7228 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-72-7229",
    sector: "base-metals",
    chapters: ["72"],
    hsRange: "72.29",
    label: "Wire of other alloy steel — except from 7227-7228",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7229 from any other heading, except from headings 7227 through 7228.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 73 — ARTICLES OF IRON OR STEEL =====================
  {
    id: "metals-73-7301-7303",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.01 through 73.03",
    label: "Rails, sheet piling, cast/rolled tubes of iron or steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7301 through 7303 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7304-11-39",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7304.11 through 7304.39",
    label: "Seamless tubes and pipes of iron or steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7304.11 through 7304.39 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7304-41-30",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "tariff item 7304.41.30",
    label: "Oil country tubular goods, casing (tariff item 7304.41.30)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7304.41.30 from subheading 7304.49 or any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7304-41",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.04.41",
    label: "Oil country tubular goods, casing (subheading 7304.41)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7304.41 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7304-49-90",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7304.49 through 7304.90",
    label: "Other OCTG and other tubes and pipes of iron or steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7304.49 through 7304.90 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7305-7307",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.05 through 73.07",
    label: "Line pipe, structural tubing, tube/pipe fittings — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      {
        effectiveFrom: "2020-07-01",
        effectiveTo: "2023-06-30",
        rvcOptions: [],
      },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification to a good of headings 7305 through 7307" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification to a good of headings 7305 through 7307" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM, Heading rule, phase 1 (2020-07-01 until 2023-06-30): 'A change to headings 7305 through 7307 from any other chapter.' VERBATIM, Heading rule, phase 2 (2023-07-01 and thereafter): '(a) A change to headings 7305 through 7307 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; or (b) A change to headings 7305 through 7307 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 or headings 7301 through 7326 is originating; or (c) No change in tariff classification to a good of headings 7305 through 7307, provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' Alternative (b) is a WEIGHT-content condition, not an RVC method — the calculator must evaluate it by weight of the specified steel-heading materials, not by the TV/NC formulas. AS OF dataAsOf (2026-09-28) ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7308-structures",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7308.10, 7308.20, 7308.30, 7308.40, 7308.90",
    label: "Structures and parts of structures of iron/steel — TWO-PHASE subheading rules",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2022-06-30", rvcOptions: [] },
      {
        effectiveFrom: "2022-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "7308.10 and 7308.30 only, alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 65, condition: "7308.10 and 7308.30 only, alternative (c): no change in tariff classification" },
          { method: "transaction-value", thresholdPercent: 65, condition: "7308.20 and 7308.40 only, alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 55, condition: "7308.20 and 7308.40 only, alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 65, condition: "7308.90 ONLY, alternative (c): regional value content of not less than 65 percent where the net cost method is used — NO transaction-value option stated in GN 11 for 7308.90" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2022-07-01, applies to each of 7308.10/20/30/40/90): '(a) A change to subheading [7308.xx] from any other heading, except for changes resulting from the following processes performed on angles, shapes, or sections of heading 7216: (i) drilling, punching, notching, cutting, cambering, or sweeping, whether performed individually or in combination; (ii) adding attachments or weldments for composite construction; (iii) adding attachments for handling purposes; (iv) adding weldments, connectors or attachments to H-sections or I-sections, provided that the maximum dimension of the weldments, connectors, or attachments is not greater than the dimension between the inner surfaces of the flanges of the H-sections or I-sections; (v) painting, galvanizing, or otherwise coating; or (vi) adding a simple base plate without stiffening elements, individually or in combination with drilling, punching, notching, or cutting, to create an article suitable as a column.' VERBATIM phase 2 (2022-07-01 and thereafter): '(a) A change to subheading [7308.xx] from any other heading, except from headings 7208, 7211, 7216, 7225 or 7226; or (b) A change to subheading [7308.xx] from headings 7208, 7211, 7216, 7225, or 7226, provided that at least 70 percent by weight of the materials of headings 7208, 7211, 7216, 7225 and 7226 is originating; or (c) No change in tariff classification to a good of subheading [7308.xx] provided there is a regional value content of not less than:' — where the (c) thresholds differ per subheading: 7308.10 and 7308.30: 75 TV / 65 NC; 7308.20 and 7308.40: 65 TV / 55 NC; 7308.90: 65 NC ONLY (GN 11 states no transaction-value option for 7308.90 — do not invent one). Alternative (b) is a WEIGHT-content condition. AS OF dataAsOf (2026-09-28) ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7309-7311",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.09 through 73.11",
    label: "Tanks and cisterns of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7309 through 7311 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7312-10",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7312.10",
    label: "Stranded wire, ropes and cables of iron/steel — TWO-PHASE rule (phase 2 begins 2023-01-01)",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2022-12-31", rvcOptions: [] },
      {
        effectiveFrom: "2023-01-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification to a good of subheading 7312.10" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification to a good of subheading 7312.10" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-01-01): '(a) A change to subheading 7312.10 from any other heading.' VERBATIM phase 2 (2023-01-01 and thereafter): '(a) A change to subheading 7312.10 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; (b) A change to subheading 7312.10 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or (c) No change in tariff classification to a good of subheading 7312.10, provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' NOTE the phase-2 start is JANUARY 1, 2023 for this rule (unlike the July 1, 2023 dates of the 7305-7307/7313/7314/7315.82-89/7317 family). AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7312-90",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7312.90",
    label: "Other stranded wire etc. of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7312.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7313",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.13",
    label: "Barbed wire etc. of iron/steel — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2023-06-30", rvcOptions: [] },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification to a good of heading 7313" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification to a good of heading 7313" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-07-01): '(a) A change to heading 7313 from any other heading.' VERBATIM phase 2 (2023-07-01 and thereafter): '(a) A change to heading 7313 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; (b) A change to heading 7313 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or c) No change in tariff classification to a good of heading 7313, provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7314-12-14",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7314.12 through 7314.14",
    label: "Woven cloth of iron/steel wire (grill, netting, fencing)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7314.12 through 7314.14 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7314-19",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7314.19",
    label: "Other cloth, grill and netting of iron/steel — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2023-06-30", rvcOptions: [] },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-07-01): '(a) A change to subheading 7314.19 from any other heading.' VERBATIM phase 2 (2023-07-01 and thereafter): '(a) A change to subheading 7314.19 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; (b) A change to subheading 7314.19 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or (c) No change in tariff classification to a good of subheading 7314.19, provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7314-20",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7314.20",
    label: "Endless belts of iron/steel wire",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7314.20 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7314-31-49",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7314.31 through 7314.49",
    label: "Woven or latticed cloth of copper/other base metal wire — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2023-06-30", rvcOptions: [] },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-07-01): '(a) A change to subheadings 7314.31 through 7314.49 from any other heading.' VERBATIM phase 2 (2023-07-01 and thereafter): '(a) A change to subheadings 7314.31 through 7314.49 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; (b) A change to subheadings 7314.31 through 7314.49 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or (c) No change in tariff classification to a good of subheadings 7314.31 through 7314.49 provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7314-50",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7314.50",
    label: "Chains of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7314.50 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7315-11-12",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7315.11 through 7315.12",
    label: "Transmission/bucket elevator belts of iron/steel",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 7315.11 through 7315.12 from any other heading; or (B) A change to subheadings 7315.11 through 7315.12 from subheading 7315.19, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 7315.19" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 7315.19" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7315-19",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7315.19",
    label: "Other transmission belts of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7315.19 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7315-20-81",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7315.20 through 7315.81",
    label: "Roller chain and other chains of iron/steel",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 7315.20 through 7315.81 from any other heading; or (B) A change to subheadings 7315.20 through 7315.81 from subheading 7315.90, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 7315.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 7315.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7315-82-89",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7315.82 through 7315.89",
    label: "Self-locking washers and other chain parts of iron/steel — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      {
        effectiveFrom: "2020-07-01",
        effectiveTo: "2023-06-30",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 60, condition: "Phase-1 alternative (b): change from subheading 7315.90" },
          { method: "net-cost", thresholdPercent: 50, condition: "Phase-1 alternative (b): change from subheading 7315.90" },
        ],
      },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-07-01): '(a) A change to subheadings 7315.82 through 7315.89 from any other heading; or (b) A change to subheadings 7315.82 through 7315.89 from subheading 7315.90, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (i) 60 percent where the transaction value method is used, or (ii) 50 percent where the net cost method is used.' VERBATIM phase 2 (2023-07-01 and thereafter): '(a) A change to subheadings 7315.82 through 7315.89 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; (b) A change to subheadings 7315.82 through 7315.89 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or (c) No change in tariff classification to a good of subheadings 7315.82 through 7315.89 provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7315-90",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7315.90",
    label: "Other chain parts of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7315.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7316",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.16",
    label: "Anchors of iron/steel — except from 7312 or 7315",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7316 from any other heading, except from headings 7312 or 7315.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7317",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.17",
    label: "Nails, tacks, staples of iron/steel/copper — TWO-PHASE rule",
    ruleBasis: "tariff-shift-or-rvc",
    phases: [
      { effectiveFrom: "2020-07-01", effectiveTo: "2023-06-30", rvcOptions: [] },
      {
        effectiveFrom: "2023-07-01",
        rvcOptions: [
          { method: "transaction-value", thresholdPercent: 75, condition: "Alternative (c): no change in tariff classification to a good of heading 7317" },
          { method: "net-cost", thresholdPercent: 65, condition: "Alternative (c): no change in tariff classification to a good of heading 7317" },
        ],
      },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM phase 1 (2020-07-01 until 2023-07-01): '(a) A change to heading 7317 from any other heading, except from heading 7318.' VERBATIM phase 2 (2023-07-01 and thereafter): '(a) A change to heading 7317 from any other heading, except from headings 7208 through 7229 or 7301 through 7326; or (b) A change to heading 7317 from headings 7208 through 7229 or 7301 through 7326, provided that at least 70 percent by weight of the materials of headings 7208 through 7229 and 7301 through 7326 is originating; or (c) No change in tariff classification to a good of heading 7317 provided there is a regional value content of not less than: (i) 75 percent where the transaction value method is used; or (ii) 65 percent where the net cost method is used.' NOTE phase 2 removes the old 7318 exception and replaces it with the steel-heading carve-outs. AS OF dataAsOf ONLY phase 2 is in force.",
    sources: SRC,
  },
  {
    id: "metals-73-7318",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.18",
    label: "Screws, bolts, nuts of iron/steel — except from 7317",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7318 from any other heading, except from heading 7317.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7319-7320",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.19 through 73.20",
    label: "Screw threads; springs of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7319 through 7320 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-11-30",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "tariff item 7321.11.30",
    label: "Cooking appliances, gas type (tariff item 7321.11.30)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7321.11.30 from any other subheading, except from tariff items 7321.90.10, 7321.90.20 or 7321.90.40.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-11",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.21.11",
    label: "Cooking appliances, gas type (subheading)",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheading 7321.11 from any other heading; or (B) A change to subheading 7321.11 from subheading 7321.90, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used, or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 7321.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 7321.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-12-89",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7321.12 through 7321.89",
    label: "Other cooking appliances of iron/steel",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 7321.12 through 7321.89 from any other heading; or (B) A change to subheadings 7321.12 through 7321.89 from subheading 7321.90, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 7321.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 7321.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-90-10",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "tariff item 7321.90.10",
    label: "Parts of cooking appliances (tariff item 7321.90.10)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7321.90.10 from any other tariff item.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-90-20",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "tariff item 7321.90.20",
    label: "Parts of cooking appliances (tariff item 7321.90.20)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7321.90.20 from any other tariff item.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-90-40",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "tariff item 7321.90.40",
    label: "Parts of cooking appliances (tariff item 7321.90.40)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7321.90.40 from any other tariff item.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7321-90",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.21.90",
    label: "Parts of cooking appliances (subheading)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7321.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7322-7323",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.22 through 73.23",
    label: "Radiators and parts thereof of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7322 through 7323 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7324-10-29",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "7324.10 through 7324.29",
    label: "Sinks and wash basins of iron/steel; sanitary ware",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 7324.10 through 7324.29 from any other heading; or (B) A change to subheadings 7324.10 through 7324.29 from subheading 7324.90, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 7324.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 7324.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7324-90",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.24.90",
    label: "Other sanitary ware of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7324.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-73-7325-7326",
    sector: "base-metals",
    chapters: ["73"],
    hsRange: "73.25 through 73.26",
    label: "Cast articles and other articles of iron/steel",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7325 through 7326 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 74 — COPPER =====================
  {
    id: "metals-74-7401-7403",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.01 through 74.03",
    label: "Copper mattes, cement copper, refined copper — except from 7404 waste/scrap unless RVC met",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to headings 7401 through 7403 from any other heading, including another heading within that group, except from heading 7404; or (B) A change to headings 7401 through 7403 from heading 7404, whether or not there is also a change from any other heading, including another heading within that group, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from heading 7404 (copper waste and scrap)" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from heading 7404 (copper waste and scrap)" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7404",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.04",
    label: "Copper waste and scrap",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of heading 7404 from any other good within that heading or any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7405-7407",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.05 through 74.07",
    label: "Master alloys, copper powders, bars/rods/profiles of copper",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to headings 7405 through 7407 from any other chapter; or (B) A change to headings 7405 through 7407 from headings 7401 through 7402 or tariff item 7404.00.30, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from headings 7401-7402 or tariff item 7404.00.30" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from headings 7401-7402 or tariff item 7404.00.30" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7408-11-60",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "tariff item 7408.11.60",
    label: "Refined copper wire (tariff item 7408.11.60)",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to tariff item 7408.11.60 from any other chapter; or (B) A change to tariff item 7408.11.60 from headings 7401 through 7402 or tariff item 7404.00.30, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from headings 7401-7402 or tariff item 7404.00.30" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from headings 7401-7402 or tariff item 7404.00.30" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7408-11",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.08.11",
    label: "Refined copper wire (subheading) — except from 7407",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7408.11 from any other heading, except from heading 7407.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7408-19-29",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "7408.19 through 7408.29",
    label: "Other copper wire — except from 7407",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7408.19 through 7408.29 from any other heading, except from heading 7407.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7409",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.09",
    label: "Copper plates, sheets and strip",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7409 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7410",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.10",
    label: "Copper foil — except from 7409",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7410 from any other heading, except from heading 7409.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7411",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.11",
    label: "Copper tubes and pipes — except from certain 7407 tariff items or 7409",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7411 from any other heading, except from tariff items 7407.10.15, 7407.21.15, 7407.29.16 or heading 7409.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7412",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.12",
    label: "Copper tube/pipe fittings — except from 7411",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7412 from any other heading, except from heading 7411.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7413",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.13",
    label: "Stranded wire and cables of copper — RVC route from 7407-7408",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to heading 7413 from any other heading, except from headings 7407 through 7408; or (B) A change to heading 7413 from headings 7407 through 7408, whether or not there is also a change from any other heading, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from headings 7407 through 7408" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from headings 7407 through 7408" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7415-7418",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "74.15 through 74.18",
    label: "Copper nails, screws, household articles, sanitary ware",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7415 through 7418 from any other heading, including another heading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7419-10",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "7419.10",
    label: "Copper chain and parts thereof — except from 7407",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7419.10 from any other heading, except from heading 7407.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7419-91",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "7419.91",
    label: "Woven cloth of copper wire",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7419.91 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-74-7419-99",
    sector: "base-metals",
    chapters: ["74"],
    hsRange: "7419.99",
    label: "Other articles of copper",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheading 7419.99 from any other good within that subheading or any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 75 — NICKEL =====================
  {
    id: "metals-75-7501-7504",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "75.01 through 75.04",
    label: "Nickel mattes, oxides, mattes, waste and scrap, powders",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7501 through 7504 from any other heading, including another heading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-75-7505-11-12",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "7505.11 through 7505.12",
    label: "Nickel bars, rods and profiles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7505.11 through 7505.12 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-75-7505-21-22",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "7505.21 through 7505.22",
    label: "Nickel plates, sheets and strip — process condition for bar/rod input",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to subheadings 7505.21 through 7505.22 from any other heading; or (B) A change to subheadings 7505.21 through 7505.22 from subheadings 7505.11 through 7505.12, whether or not there is also a change from any other heading, provided that, if bar or rod is used, the cross-sectional area of the bar or rod is reduced by at least 50 percent.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "Alternative (B) is a process requirement (cross-sectional-area reduction of at least 50 percent for bar/rod inputs), not an RVC threshold. No percentage RVC is stated in GN 11 for this rule.",
    sources: SRC,
  },
  {
    id: "metals-75-7506-10-05",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "tariff item 7506.10.05",
    label: "Nickel foil (tariff item 7506.10.05)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7506.10.05 from any other tariff item.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-75-7506-20-05",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "tariff item 7506.20.05",
    label: "Nickel flakes and powder (tariff item 7506.20.05)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to tariff item 7506.20.05 from any other tariff item.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-75-7506",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "75.06",
    label: "Nickel foil, flakes and powder (heading)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7506 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-75-7507-11-7508-90",
    sector: "base-metals",
    chapters: ["75"],
    hsRange: "7507.11 through 7508.90",
    label: "Nickel tubes, pipes, fittings, articles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 7507.11 through 7508.90 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 76 — ALUMINUM =====================
  {
    id: "metals-76-7601",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.01",
    label: "Unwrought aluminum",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7601 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7602",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.02",
    label: "Aluminum waste and scrap",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7602 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7603",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.03",
    label: "Aluminum powders and flakes",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7603 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7604",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.04",
    label: "Aluminum bars, rods and profiles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7604 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7605",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.05",
    label: "Aluminum wire — except from 7604 or 7606",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7605 from any other heading, except from headings 7604 or 7606.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7606",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.06",
    label: "Aluminum plates, sheets and strip",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7606 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7607",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.07",
    label: "Aluminum foil",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7607 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7608-7609",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.08 through 76.09",
    label: "Aluminum tubes, pipes and fittings",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7608 through 7609 from any heading outside that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7610-7613",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.10 through 76.13",
    label: "Aluminum structures, tanks, casks, foil-backed panels, stranded wire",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7610 through 7613 from any other heading, including another heading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7614",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.14",
    label: "Stranded wire and cables of aluminum (electrical) — except from 7604-7605",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 7614 from any other heading, except from headings 7604 through 7605.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-76-7615-7616",
    sector: "base-metals",
    chapters: ["76"],
    hsRange: "76.15 through 76.16",
    label: "Aluminum household articles, sanitary ware, other articles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7615 through 7616 from any other heading, including another heading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 78 — LEAD =====================
  {
    id: "metals-78-7801-7802",
    sector: "base-metals",
    chapters: ["78"],
    hsRange: "78.01 through 78.02",
    label: "Refined lead; lead waste and scrap",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7801 through 7802 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-78-7804-11-20",
    sector: "base-metals",
    chapters: ["78"],
    hsRange: "7804.11 through 7804.20",
    label: "Lead plates, sheets, strip, foil",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to subheadings 7804.11 through 7804.20 from any other subheading, including another subheading within that group; or (B) A change to foil of a thickness not exceeding 0.15 mm (excluding backing) of subheading 7804.11 from within that subheading, whether or not there is also a change from any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-78-7806",
    sector: "base-metals",
    chapters: ["78"],
    hsRange: "78.06",
    label: "Other articles of lead",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of heading 7806 from any other good within that heading or any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 79 — ZINC =====================
  {
    id: "metals-79-7901-7902",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "79.01 through 79.02",
    label: "Unwrought zinc; zinc waste and scrap",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 7901 through 7902 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-79-7903-10",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "7903.10",
    label: "Zinc powders and flakes",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7903.10 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-79-7903-90",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "7903.90",
    label: "Other unwrought zinc",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 7903.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-79-7904",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "79.04",
    label: "Zinc bars, rods, profiles, wire — process condition for bar/rod input",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to heading 7904 from any other heading; or (B) A change to wire of heading 7904 from within that heading, whether or not there is also a change from any other heading, provided that, if bar or rod is used, the cross-sectional area of the bar or rod is reduced by at least 50 percent.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-79-7905",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "79.05",
    label: "Zinc plates, sheets, strip, foil",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to heading 7905 from any other heading; or (B) A change to foil of a thickness not exceeding 0.15 mm (excluding backing) of heading 7905 from within that heading, whether or not there is also a change from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-79-7907",
    sector: "base-metals",
    chapters: ["79"],
    hsRange: "79.07",
    label: "Other articles of zinc",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of heading 7907 from any other good within that heading or any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 80 — TIN =====================
  {
    id: "metals-80-8001-8002",
    sector: "base-metals",
    chapters: ["80"],
    hsRange: "80.01 through 80.02",
    label: "Unwrought tin; tin waste and scrap",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8001 through 8002 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-80-8003",
    sector: "base-metals",
    chapters: ["80"],
    hsRange: "80.03",
    label: "Tin bars, rods, profiles, wire — process condition for bar/rod input",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to heading 8003 from any other heading; or (B) A change to wire of heading 8003 from within that heading, whether or not there is also a change from any other heading, provided that, if bar or rod is used, the cross-sectional area of the bar or rod is reduced by at least 50 percent.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-80-8007",
    sector: "base-metals",
    chapters: ["80"],
    hsRange: "80.07",
    label: "Other articles of tin",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of heading 8007 from any other good within that heading or any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 81 — OTHER BASE METALS =====================
  {
    id: "metals-81-8101-10-97",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8101.10 through 8101.97",
    label: "Tungsten and articles thereof (subdivided provisions)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8101.10 through 8101.97 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8101-99",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8101.99",
    label: "Other articles of tungsten",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of subheading 8101.99 from any other good within that subheading or any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8102-10-8107-90",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8102.10 through 8107.90",
    label: "Molybdenum, tantalum, magnesium, cobalt, bismuth, cadmium, titanium, antimony, manganese articles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8102.10 through 8107.90 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8108-20",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8108.20",
    label: "Zirconium unwrought, waste and scrap, powders",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheading 8108.20 from any other chapter; or (B) A change from any other subheading whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60 },
      { method: "net-cost", thresholdPercent: 50 },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8108-30",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8108.30",
    label: "Zirconium wrought bars, rods, profiles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 8108.30 from any other subheading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8108-90",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8108.90",
    label: "Other articles of zirconium",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheading 8108.90 from any other chapter; or (B) A change to subheading 8108.90 from any other subheading, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60 },
      { method: "net-cost", thresholdPercent: 50 },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8109-20-8110-90",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8109.20 through 8110.90",
    label: "Hafnium and gallium articles",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8109.20 through 8110.90 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8111",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "81.11",
    label: "Articles of manganese — split rule for manganese powders/articles",
    ruleBasis: "tariff-shift",
    tariffShiftRule:
      "(A) A change to manganese powders or articles of manganese of heading 8111 from any other good of heading 8111; or (B) A change to any other good of heading 8111 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8112-12-59",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8112.12 through 8112.59",
    label: "Beryllium, chromium, thallium and articles thereof",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8112.12 through 8112.59 from any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8112-92-99",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "8112.92 through 8112.99",
    label: "Articles of beryllium, chromium etc.",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to a good of any of subheadings 8112.92 through 8112.99 from any other good within that subheading or any other subheading, including another subheading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-81-8113",
    sector: "base-metals",
    chapters: ["81"],
    hsRange: "81.13",
    label: "Cermets and articles thereof",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 8113 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 82 — TOOLS AND CUTLERY =====================
  {
    id: "metals-82-8201",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "82.01",
    label: "Hand tools: spades, shovels, axes etc.",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to heading 8201 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8202-10-20",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8202.10 through 8202.20",
    label: "Hand saws and saw blades",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8202.10 through 8202.20 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8202-31",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8202.31",
    label: "Circular saw blades — RVC route from 8202.39",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheading 8202.31 from any other chapter; or (B) A change to subheadings 8202.31 from subheading 8202.39, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8202.39" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8202.39" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8202-39-99",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8202.39 through 8202.99",
    label: "Other saw blades (bandsaw blades etc.)",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8202.39 through 8202.99 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8203-8206",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "82.03 through 82.06",
    label: "Files, pliers, hammers, drills, taps, interchangeable tools",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8203 through 8206 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8207-13",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8207.13",
    label: "Rock-drilling bits with working part of sintered metal carbide — RVC route from 8207.19",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheading 8207.13 from any other chapter; or (B) A change to subheading 8207.13 from subheading 8207.19, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8207.19" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8207.19" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8207-19-90",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8207.19 through 8207.90",
    label: "Other interchangeable tools of base metal",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8207.19 through 8207.90 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8208-8210",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "82.08 through 82.10",
    label: "Knives and cutting blades, mechanical appliances for kitchen, etc.",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8208 through 8210 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8211-10",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8211.10",
    label: "Knives with cutting blades, serrated or not",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 8211.10 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8211-91-93",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8211.91 through 8211.93",
    label: "Blades for knives — RVC route from 8211.95",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 8211.91 through 8211.93 from any other chapter; or (B) A change to subheadings 8211.91 through 8211.93 from subheading 8211.95, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8211.95" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8211.95" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8211-94-95",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "8211.94 through 8211.95",
    label: "Handles and blades of base metal for knives",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8211.94 through 8211.95 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-82-8212-8215",
    sector: "base-metals",
    chapters: ["82"],
    hsRange: "82.12 through 82.15",
    label: "Razors, scissors, sets of table articles of base metal",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8212 through 8215 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },

  // ===================== CHAPTER 83 — MISCELLANEOUS ARTICLES OF BASE METAL =====================
  {
    id: "metals-83-chapter-rule-1",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "Chapter 83 chapter rules",
    label: "Chapter 83 Chapter rule 1 and underscored designations — automotive carryover (CROSS-REFERENCE)",
    ruleBasis: "special",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "VERBATIM Chapter rule 1: 'For the purposes of the subdivisions pertaining to this chapter, whenever the subdivision designation is underscored, the provisions of subdivision (k) of this note may apply to goods for use in a motor vehicle of chapter 87.' VERBATIM Subheading rule: 'The underscoring of the designations in subdivision 1 pertain to goods provided for in subheadings 8301.10 through 8301.50 for use in a motor vehicle of chapter 87.' CROSS-REFERENCE RECORD — contains no thresholds of its own. GN 11(k) is the automotive-parts provision owned by the AUTOMOTIVE_SECTOR_FILE. Goods of subheadings 8301.10-8301.50 (locks) used in a motor vehicle of chapter 87 may be governed by that regime; do not compute any automotive threshold from this file. The plain-text OCR of the official PDF cannot visually preserve underscored designations — a human audit against the original PDF's typography is required (see audit checklist).",
    sources: SRC,
  },
  {
    id: "metals-83-8301-10-50",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "8301.10 through 8301.50",
    label: "Padlocks, locks for vehicles, door locks — RVC route from 8301.60 (underscored: automotive (k) may apply)",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 8301.10 through 8301.50 from any other chapter; or (B) A change to subheadings 8301.10 through 8301.50 from subheading 8301.60, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8301.60" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8301.60" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    notes:
      "The GN 11 designations for this subdivision are underscored — for goods used in a motor vehicle of chapter 87, subdivision (k) of GN 11 may apply (automotive file owns that regime).",
    sources: SRC,
  },
  {
    id: "metals-83-8301-60-70",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "8301.60 through 8301.70",
    label: "Locks for furniture, other base-metal locks",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheadings 8301.60 through 8301.70 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8302-8304",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.02 through 83.04",
    label: "Lock fittings, mountings, hinges, keys; safes; nameplates",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8302 through 8304 from any other heading, including another heading within that group.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8305-10-20",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "8305.10 through 8305.20",
    label: "Ring binders, letter clips — RVC route from 8305.90",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 8305.10 through 8305.20 from any other chapter; or (B) A change to subheadings 8305.10 through 8305.20 from subheading 8305.90, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8305.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8305.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8305-90",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.05.90",
    label: "Other office fittings of base metal",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 8305.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8306-8307",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.06 through 83.07",
    label: "Statuettes, frames, flexible tubing of base metal",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8306 through 8307 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8308-10-20",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "8308.10 through 8308.20",
    label: "Hooks and eyes, snap fasteners — RVC route from 8308.90",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 8308.10 through 8308.20 from any other chapter; or (B) A change to subheadings 8308.10 through 8308.20 from subheading 8308.90, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8308.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8308.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8308-90",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.08.90",
    label: "Other parts of hooks/eyes and fasteners",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 8308.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8309-8310",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.09 through 83.10",
    label: "Bottle closures; sign plates of base metal",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to headings 8309 through 8310 from any other chapter.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8311-10-30",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "8311.10 through 8311.30",
    label: "Steel wool; prepared wool; pot scourers — RVC route from 8311.90",
    ruleBasis: "tariff-shift-or-rvc",
    tariffShiftRule:
      "(A) A change to subheadings 8311.10 through 8311.30 from any other chapter; or (B) A change to subheadings 8311.10 through 8311.30 from subheading 8311.90, whether or not there is also a change from any other chapter, provided there is a regional value content of not less than: (1) 60 percent where the transaction value method is used; or (2) 50 percent where the net cost method is used.",
    rvcOptions: [
      { method: "transaction-value", thresholdPercent: 60, condition: "Alternative (B): change from subheading 8311.90" },
      { method: "net-cost", thresholdPercent: 50, condition: "Alternative (B): change from subheading 8311.90" },
    ],
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
  {
    id: "metals-83-8311-90",
    sector: "base-metals",
    chapters: ["83"],
    hsRange: "83.11.90",
    label: "Other articles of steel wool etc.",
    ruleBasis: "tariff-shift",
    tariffShiftRule: "A change to subheading 8311.90 from any other heading.",
    effectiveFrom: "2020-07-01",
    verified: true,
    auditStatus: "human_verified",
    sources: SRC,
  },
];

export const BASE_METALS_SECTOR_FILE: UsmcaSectorFile = {
  sector: "base-metals",
  chaptersCovered: BASE_METALS_CHAPTERS,
  dataAsOf: "2026-09-28",
  mergeEligible: true,
  auditStatus: "human_verified",
  rules: BASE_METALS_RULES,
  watchItems: [
    "PHASED STEEL RULES ARE DATE-SENSITIVE: as of dataAsOf (2026-09-28) the phase-2 rules are the only ones in force for 7305-7307, 7308.10/20/30/40/90, 7312.10 (from 2023-01-01), 7313, 7314.19, 7314.31-49, 7315.82-89 and 7317. The calculator must select the rule version by entry/claim date. Note 7308.90 phase 2 alternative (c) provides a 65 percent NET COST method option ONLY — GN 11 states no transaction-value option for 7308.90; do not invent one.",
    "The 70-percent-by-weight conditions in the phase-2 steel rules are WEIGHT-content tests on materials of headings 7208-7229 / 7301-7326 (or 7208/7211/7216/7225/7226 for 7308.x) — not TV/NC RVC. The schema's rvcOptions captures the paired (c) RVC alternatives; the weight alternative is preserved verbatim in notes.",
    "Section 232 steel and aluminum actions are a separate national-security tariff regime — a Chapter 72/73 (steel) or 76 (aluminum) good can be fully USMCA-originating and still owe Section 232 duties. Keep the two regimes separate in the calculator's output.",
    "Chapter 83 chapter rule: underscored designations (8301.10-8301.50 for use in a motor vehicle of chapter 87) may trigger GN 11(k), owned by the automotive sector file. Plain-text OCR cannot confirm which other chapter 83 designations are underscored — human audit against the official PDF typography required.",
    "GN 11(b)(iv) fallback (60 percent TV / 50 percent NC for same-subheading parts failures) is owned by the core types file and deliberately not restated here.",
    "USMCA joint review (around 2026) may revise rules of origin — re-verify against the current HTSUS GN 11 revision before relying on this file for new claim periods.",
  ],
  sourceFirewall: {
    treatyBaseline: "USMCA Chapter 4 / Annex 4-B (Product-Specific Rules of Origin), Chapters 72-83",
    usImplementation: "HTSUS General Note 11 (2026 Revision 15), subdivision (o) — chapters 72-83 table incl. heading/subheading rules with effective-date phases / 19 CFR Part 182",
    excludedAgreements: [
      "NAFTA (superseded — GN 12(t)/Annex 401 chapters 72-83 rules lack the USMCA phased steel rules and remain indexed on usitc.gov archives)",
      "KORUS, CAFTA-DR, CPTPP and other FTAs with similar chapters 72-83 tariff-shift phrasing",
      "Section 232 steel/aluminum regimes (separate national-security tariff regime, not origin rules)",
      "GN 11(k) automotive-parts regime (owned by AUTOMOTIVE_SECTOR_FILE; referenced here, never restated)",
    ],
  },
};

export default BASE_METALS_SECTOR_FILE;